// ===========================================================================
// ACME Automotive — CAMPAIGN-SCOPED signals (filter-specific)
// One concrete signal per selectable campaign. These are NOT the holistic
// "brand view" insights — each carries `scoped: true` and a `campaign` id, so
// it surfaces on the Signals page ONLY when that campaign is selected in the
// filter layer. Fields (productLine/division/channels/geos) mirror the campaign
// def in mock-data.ts so the filter binding matches exactly.
// ===========================================================================
import type { Insight } from '@/types';
import {
  type InsightVisual, TEAL, RED, BLUE, PURPLE, GOLD, MUTED, GRID,
} from './insight-visual-types';
import { at } from './clients/_shared';

export const AUTO_CAMPAIGN_INSIGHTS: Insight[] = [
  // ─────────────────────────── TIER 1 — NATIONAL ───────────────────────────
  {
    id: 'ins-auto-cmp-ford-lightning-launch-hero', createdAt: at(0, '06:02:00'),
    enterprise: 'ford-canada', category: 'tactical-efficiency', scope: 'campaign', scoped: true,
    division: 'tier-1', productLine: 'lightning', campaign: 'ford-lightning-launch-hero',
    channels: ['ctv', 'ttd', 'google-search', 'instagram', 'ooh'], geos: ['national'],
    title: 'The Electric Pickup Launch Hero Is Front-Loaded on CTV — but Launch Search Intent Is Now Spiking, and That’s Where the Next Dollar Converts',
    summary: 'The $12.4M launch hero did its job building awareness on CTV and OOH, but the curve has turned: connected-TV reach on the core truck-intender audience is past its efficient point while branded "electric pickup" search has tripled in the two weeks since launch. The money is still weighted to the top-funnel channels that opened the launch, not the high-intent search and conquest demand the launch created. Shift the post-peak CTV tail into search and Trade Desk conquest while intent is live.',
    evidence: [
      'CTV reach frequency on truck-intenders is past the ~8× point where launch awareness stops compounding.',
      'Branded "electric pickup" + conquest search up ~210% in the two weeks since the hero launched.',
      'Search holds only ~14% of the launch budget despite the steepest conversion curve right now.',
      'STRATIS reads the launch awareness→intent handoff continuously; a flight plan books the CTV tail as “working.”',
    ],
    confidence: 0.88,
    impactEstimate: 'Moving the saturated CTV tail (~$1.6M) into launch search and conquest is projected to lift launch conversions ~12% without adding budget — captured while intent is peaking, not after the flight.',
    recommendedAction: 'Cap the launch CTV tail at its efficient point and redeploy into branded search and Trade Desk conquest against the EV disruptor. STRATIS rebalances as the launch intent curve moves.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Cap the post-peak CTV launch tail', subtitle: 'AWARENESS HAS COMPOUNDED', type: 'budget', completed: false },
      { id: 's2', title: 'Redeploy into launch search + conquest', subtitle: 'WHERE INTENT IS SPIKING NOW', type: 'budget', completed: false },
      { id: 's3', title: 'Hold the awareness→intent handoff live', subtitle: 'STRATIS REBALANCES', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-f150-built-tough', createdAt: at(0, '06:04:00'),
    enterprise: 'ford-canada', category: 'creative-performance', scope: 'campaign', scoped: true,
    division: 'tier-1', productLine: 'f150', campaign: 'ford-f150-built-tough',
    channels: ['ctv', 'ttd', 'google-search', 'ooh'], geos: ['national'],
    title: 'The Built-Tough Hero Spot Has Lost ~16% of Its Pull in Three Weeks at Flat Spend — That’s Wear-Out on the Full-Size Truck Flight, Not a Delivery Problem',
    summary: 'The flagship truck spot is tiring. Its pull with truck-intenders is down ~16% over three weeks even though spend and audience haven’t changed, and response now drops with each additional viewing — the fingerprint of creative wear-out, not a buying problem. A fresher towing-capability cut running beside it is holding steady. Re-tuning the CTV buy would fix nothing; the move is a refresh.',
    evidence: [
      'Built-Tough hero pull down ~16% over three weeks at flat spend and steady audience.',
      'Response falls with each extra viewing — wear-out, not a delivery shift.',
      'A fresher towing/payload cut is holding its rate beside the tired hero.',
      'STRATIS separates wear-out from delivery so the team doesn’t re-tune the buy by mistake.',
    ],
    confidence: 0.87,
    impactEstimate: 'Refreshing before the decay deepens is projected to recover ~14% of the flight’s cost-per-result and avoids a wasted buy change that wouldn’t fix wear-out.',
    recommendedAction: 'Cap the tired hero, promote the fresher capability cut, and brief a new execution for the over-exposed truck audience. STRATIS flags the refresh window.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Confirm wear-out before touching the buy', subtitle: 'FREQUENCY, NOT DELIVERY', type: 'creative', completed: false },
      { id: 's2', title: 'Promote the fresher capability cut', subtitle: 'IT’S HOLDING ITS RATE', type: 'creative', completed: false },
      { id: 's3', title: 'Brief a new execution for the worn audience', subtitle: 'BEFORE IT COSTS RESULTS', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-mach-e-defense', createdAt: at(0, '06:06:00'),
    enterprise: 'ford-canada', category: 'competitive-macro', scope: 'campaign', scoped: true,
    division: 'tier-1', productLine: 'mach-e', campaign: 'ford-mach-e-defense',
    channels: ['google-search', 'instagram', 'tiktok', 'ttd'], geos: ['national'],
    title: 'The Electric Crossover Defense Is Losing the Comparison Auction to a Compact Electric SUV — Cost-per-Consideration Is Drifting Up While the Rival Outbids Us on Our Own Conquest Terms',
    summary: 'This campaign is on the back foot. The compact-electric-SUV rival is bidding aggressively on the exact "electric crossover vs" comparison terms the defense depends on, and our cost-per-consideration has drifted up while consideration itself softens (the only nameplate flight trending down). The defense is funded as always-on awareness, not as a focused auction fight where the contest is actually happening. Concentrate weight on the contested comparison terms and the objection creative, not broad reach.',
    evidence: [
      'The rival is outbidding the defense on ~40% of high-intent "electric crossover vs" comparison queries.',
      'Cost-per-consideration on the flight is drifting up while consideration trends down quarter-to-date.',
      'The range/charging objection creative holds only a thin share of the defense’s impressions.',
      'STRATIS ties the consideration slip to the rival’s comparison-auction entry — cause, not guess.',
    ],
    confidence: 0.84,
    impactEstimate: 'Concentrating spend on the contested comparison terms and surfacing the objection creative is projected to stabilize cost-per-consideration and recover ~9% of lost consideration share.',
    recommendedAction: 'Move broad-reach defense budget into the contested comparison auction and put the range/charging objection ad live there. STRATIS alerts as the rival’s bid pressure shifts.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Concentrate on the contested comparison terms', subtitle: 'WHERE THE FIGHT ACTUALLY IS', type: 'bidding', completed: false },
      { id: 's2', title: 'Put the range/charging objection ad live', subtitle: 'ANSWER THE SWITCH HESITATION', type: 'creative', completed: false },
      { id: 's3', title: 'Track the rival’s bid pressure daily', subtitle: 'STRATIS HOLDS THE LANE', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-bronco-adventure-national', createdAt: at(0, '06:08:00'),
    enterprise: 'ford-canada', category: 'creative-performance', scope: 'campaign', scoped: true,
    division: 'tier-1', productLine: 'bronco', campaign: 'ford-bronco-adventure-national',
    channels: ['ctv', 'instagram', 'tiktok', 'ttd'], geos: ['national'],
    title: 'The Rugged-SUV Vertical Trail Cut Is Converting ~1.5× the Hero on TikTok and Instagram — but It Gets Only ~13% of the Adventure Flight’s Views',
    summary: 'Ranked by conversions actually driven, the user-style vertical "trail" cut is the clear winner of the adventure flight — it converts the adventure-lifestyle audience at ~1.5× the polished hero on TikTok and Reels, where this audience lives. But delivery defaults to the CTV hero, so the proven cut is starved at ~13% of views. This is a free gain: give the winner the views, then make more like it.',
    evidence: [
      'The vertical trail cut converts ~1.5× the hero on TikTok + Instagram for adventure-lifestyle.',
      'It holds only ~13% of the flight’s views — delivery defaults to the CTV hero.',
      'The edge repeats across independent metros — not a single-market fluke.',
      'Measured on conversions driven, not last view; STRATIS keeps ranking creative this way.',
    ],
    confidence: 0.88,
    impactEstimate: 'Shifting views to the proven vertical cut lifts the flight’s conversion rate at no production cost — and tells the agency exactly what to make more of.',
    recommendedAction: 'Re-weight delivery from the hero to the winning vertical cut on social and brief more in that style. STRATIS holds the creative ranking by conversions driven.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Give the vertical trail cut the views', subtitle: 'FREE GAIN — NO NEW SPEND', type: 'creative', completed: false },
      { id: 's2', title: 'Shift social delivery off the CTV hero', subtitle: 'MEET THE AUDIENCE WHERE IT IS', type: 'creative', completed: false },
      { id: 's3', title: 'Brief more in the winning style', subtitle: 'PROVEN IDEA → MORE OF IT', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-explorer-family', createdAt: at(0, '06:10:00'),
    enterprise: 'ford-canada', category: 'competitive-macro', scope: 'campaign', scoped: true,
    division: 'tier-1', productLine: 'explorer', campaign: 'ford-explorer-family',
    channels: ['ctv', 'google-search', 'instagram', 'facebook'], geos: ['national'],
    title: 'Family Three-Row Shoppers on This Flight Are Cross-Shopping an Import Leader’s Three-Row at a Rising Rate — the Conquest Creative Isn’t Running Where They Compare',
    summary: 'The Three-Row family flight is converting, but a growing share of its audience is actively cross-shopping an import-leader three-row in the same sessions — and our conquest comparison creative is barely present in that consideration moment. The flight is weighted to broad family awareness on CTV, not to the head-to-head search and social moment where the cross-shop is decided. Surface the third-row-space and standard-features comparison where the shopping actually happens.',
    evidence: [
      '~1 in 3 reached family shoppers cross-shop the import-leader three-row in the same window.',
      'Conquest comparison creative holds a thin share of the flight’s search + social delivery.',
      'Cross-shop conversion is highest when the comparison ad lands in the consideration session.',
      'STRATIS joins cross-shop signal to delivery — no single channel report shows the overlap.',
    ],
    confidence: 0.83,
    impactEstimate: 'Surfacing the conquest comparison in the cross-shop moment is projected to lift conquest conversions ~10% at flat spend by meeting shoppers where they compare.',
    recommendedAction: 'Shift weight into head-to-head comparison search and social and put the space/features conquest creative live there. STRATIS tracks the cross-shop rate.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Fund the head-to-head comparison moment', subtitle: 'WHERE THE CROSS-SHOP IS DECIDED', type: 'budget', completed: false },
      { id: 's2', title: 'Run the space/features conquest creative there', subtitle: 'ANSWER THE COMPARISON', type: 'creative', completed: false },
      { id: 's3', title: 'Watch the cross-shop rate continuously', subtitle: 'STRATIS FLAGS THE SHIFT', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-escape-phev-izev', createdAt: at(0, '06:12:00'),
    enterprise: 'ford-canada', category: 'competitive-macro', scope: 'campaign', scoped: true,
    division: 'tier-1', productLine: 'escape-phev', campaign: 'ford-escape-phev-izev',
    channels: ['google-search', 'instagram', 'facebook', 'ttd'], geos: ['national'],
    title: 'Two Tailwinds Are Converging on the Plug-In Hybrid SUV Flight — the iZEV Rebate Window and Sustained High Gas — and the Budget Hasn’t Moved to Catch Them',
    summary: 'The PHEV flight is sitting in front of two simultaneous tailwinds: the iZEV rebate keeps the effective price down, and gas above the threshold is pushing organic "plug-in hybrid" and "save on gas" search up week over week. Demand is rising faster than the flight’s modest budget, so we’re leaving in-market intenders uncaptured. This is a lean-in, not a reallocation — fund the affordability + fuel-savings message into the demand the macro is creating.',
    evidence: [
      'Organic plug-in-hybrid / fuel-savings search up week over week as gas holds above the threshold.',
      'The iZEV rebate keeps effective price down — the affordability message is true right now.',
      'The flight is one of the smaller-funded nameplates despite the strongest demand tailwind.',
      'STRATIS triangulates gas + rebate + search and calls the window; correlation, not cause.',
    ],
    confidence: 0.85,
    impactEstimate: 'Funding the affordability + fuel-savings message into the live demand is projected to capture ~13% more in-market PHEV intenders at a lower cost per lead while the tailwinds hold.',
    recommendedAction: 'Raise the flight’s search and social weight on affordability + fuel-savings while the rebate and gas tailwinds are live. STRATIS alerts when either tailwind fades.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Lean budget into the live demand window', subtitle: 'REBATE + GAS TAILWIND', type: 'budget', completed: false },
      { id: 's2', title: 'Run the affordability + fuel-savings message', subtitle: 'IT’S TRUE RIGHT NOW', type: 'creative', completed: false },
      { id: 's3', title: 'Alert when a tailwind fades', subtitle: 'STRATIS WATCHES GAS + REBATE', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-transit-fleet', createdAt: at(0, '06:14:00'),
    enterprise: 'ford-canada', category: 'tactical-efficiency', scope: 'campaign', scoped: true,
    division: 'tier-1', productLine: 'transit', campaign: 'ford-transit-fleet',
    channels: ['linkedin', 'google-search', 'ttd'], geos: ['national'],
    title: 'LinkedIn Is Driving Fleet Demo Requests at ~2.1× the Cost-Efficiency of Programmatic on the Commercial Van Flight — but It Holds a Third of the Budget',
    summary: 'For the commercial-van fleet campaign, the buyer is a business decision-maker, and LinkedIn’s targeting against fleet/operations titles is converting demo requests at more than twice the efficiency of the programmatic display line. Yet the budget is split toward broad Trade Desk reach because it’s cheaper per impression — which is the wrong metric for a B2B conversion goal. Re-weight toward the channel that actually books fleet demos.',
    evidence: [
      'LinkedIn: ~2.1× the cost per fleet demo request of the programmatic display line.',
      'Programmatic absorbs a large share of budget on a cheap-CPM basis, not on demos booked.',
      'Fleet/operations-title targeting on LinkedIn reaches the actual decision-maker.',
      'STRATIS ranks the flight on demos booked per dollar, not impressions.',
    ],
    confidence: 0.86,
    impactEstimate: 'Re-weighting toward LinkedIn is projected to lift fleet demo requests ~15% at the same spend by funding the channel that converts the B2B buyer.',
    recommendedAction: 'Shift budget from broad programmatic into LinkedIn fleet-title targeting and keep search for in-market intent. STRATIS rebalances on demos-per-dollar.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Raise LinkedIn fleet-title budget share', subtitle: 'WHERE DEMOS GET BOOKED', type: 'budget', completed: false },
      { id: 's2', title: 'Trim broad programmatic reach', subtitle: 'CHEAP CPM ≠ B2B CONVERSION', type: 'budget', completed: false },
      { id: 's3', title: 'Rank the flight on demos per dollar', subtitle: 'NOT IMPRESSIONS', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-edge-mature', createdAt: at(0, '06:16:00'),
    enterprise: 'ford-canada', category: 'tactical-efficiency', scope: 'campaign', scoped: true,
    division: 'tier-1', productLine: 'edge', campaign: 'ford-edge-mature',
    channels: ['google-search', 'facebook', 'ttd'], geos: ['national'],
    title: 'The Midsize SUV Maintenance Flight Is Spending Awareness Dollars on a Mature Nameplate Whose Demand Is Declining — Harvest It Down to an Efficient Search Floor',
    summary: 'This is a mature, declining nameplate, but the flight still carries broad awareness weight on Facebook and Trade Desk as if it were in growth. With demand trending down, top-funnel spend here buys little incremental — the efficient play is to harvest: pull awareness back to a lean, intent-only search floor that captures the buyers still actively shopping, and free the rest for nameplates with a demand tailwind.',
    evidence: [
      'Nameplate demand is trending down — top-funnel awareness adds little incremental here.',
      'Broad Facebook + programmatic reach absorbs budget at the weakest marginal return in the portfolio.',
      'Intent-only search still captures the remaining in-market midsize shoppers efficiently.',
      'STRATIS scores the flight on marginal return and flags it as a harvest candidate.',
    ],
    confidence: 0.85,
    impactEstimate: 'Harvesting to an intent-only floor frees ~$0.9M from the portfolio’s weakest marginal spend with negligible volume loss — redeployable to tailwind nameplates.',
    recommendedAction: 'Cut broad awareness on the mature nameplate to an efficient search floor and redeploy the freed budget to nameplates with rising demand. STRATIS holds the floor.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Harvest to an intent-only search floor', subtitle: 'STOP FUNDING DECLINING AWARENESS', type: 'budget', completed: false },
      { id: 's2', title: 'Redeploy to tailwind nameplates', subtitle: 'WHERE THE NEXT DOLLAR WORKS', type: 'budget', completed: false },
      { id: 's3', title: 'Hold the efficient floor', subtitle: 'STRATIS WATCHES MARGINAL RETURN', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-brand-q2', createdAt: at(0, '06:18:00'),
    enterprise: 'ford-canada', category: 'audience-overlap', scope: 'campaign', scoped: true,
    division: 'tier-1', productLine: 'f150', campaign: 'ford-brand-q2',
    channels: ['ctv', 'ooh', 'spotify'], geos: ['national'],
    title: 'The Master-Brand Q2 Flight Stacks on Top of Every Nameplate Campaign — the Average Truck-Intender Now Sees ~21 ACME Messages a Week, Most Above the Effective Ceiling',
    summary: 'The master-brand flight buys the same broad audience the nameplate campaigns already reach, and nobody caps across them. Deduped against the live nameplate flights, the average truck-intender sees ~21 ACME messages a week — roughly double the ~10–12 range where extra exposure stops persuading. The brand flight isn’t wrong to run; it just needs to be capped against the nameplate weight so it adds reach, not redundant frequency.',
    evidence: [
      'Deduped across master-brand + nameplate flights: ~21 exposures/week to the average truck-intender.',
      'No single flight looks high — the pile-up only shows when matched to one person.',
      'Extra exposure past ~10–12/week stops persuading this audience.',
      'STRATIS dedupes across the brand and nameplate flights — no single buy sees the stack.',
    ],
    confidence: 0.9,
    impactEstimate: 'A cross-flight cap pulls weekly exposure back to the effective range and frees the over-delivered master-brand weight into net-new reach — ~12% more unique audience at flat spend.',
    recommendedAction: 'Set a portfolio cap that holds the master-brand flight against the nameplate weight and move the recovered impressions to under-reached audiences. STRATIS enforces the combined cap.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Cap master-brand against nameplate weight', subtitle: 'ONE CAP ACROSS ALL FLIGHTS', type: 'bidding', completed: false },
      { id: 's2', title: 'Move recovered weight to net-new reach', subtitle: 'ADD REACH, NOT FREQUENCY', type: 'budget', completed: false },
      { id: 's3', title: 'Enforce the combined cap continuously', subtitle: 'STRATIS DEDUPES ACROSS FLIGHTS', type: 'scheduling', completed: false },
    ],
  },

  // ─────────────────────────── TIER 2 — REGIONAL ───────────────────────────
  {
    id: 'ins-auto-cmp-ford-lightning-bc-regional', createdAt: at(0, '06:20:00'),
    enterprise: 'ford-canada', category: 'national-regional', scope: 'campaign', scoped: true,
    division: 'tier-2', productLine: 'lightning', campaign: 'ford-lightning-bc-regional',
    channels: ['google-search', 'instagram', 'facebook'], geos: ['bc'],
    title: 'The BC Electric Pickup Regional Is Running the Best Cost-per-Lead in the Country (~$148) — Its Playbook Is Sitting Unused in Four Other Regions',
    summary: 'This campaign is the proof point: at ~$148 cost-per-lead it’s converting electric-pickup demand at roughly half the cost of the Ontario regional, on the same nameplate. The difference isn’t the market — it’s the playbook: tight intent-search + local-proof social, no broad prospecting waste. That recipe is documented here and deployed nowhere else. The opportunity isn’t inside this campaign, it’s exporting what it already does.',
    evidence: [
      'BC Electric Pickup CPL ~$148 vs ~$298 for the same nameplate in Ontario.',
      'The edge traces to intent-search concentration + local-proof creative, not cheaper media.',
      'Four other regional Electric Pickup / truck flights still run broad prospecting.',
      'STRATIS reads the playbook difference across regions — no single regional report sees it.',
    ],
    confidence: 0.89,
    impactEstimate: 'Exporting the BC playbook to the trailing regional flights is projected to cut their blended CPL ~20–30%, the single biggest efficiency move available in the regional tier.',
    recommendedAction: 'Codify the BC playbook (intent-search concentration + local-proof creative) and cascade it to the trailing regions. STRATIS tracks adoption and CPL convergence.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Codify the BC ~$148 playbook', subtitle: 'WHAT ACTUALLY DRIVES THE EDGE', type: 'targeting', completed: false },
      { id: 's2', title: 'Cascade it to the trailing regions', subtitle: 'EXPORT, DON’T REINVENT', type: 'budget', completed: false },
      { id: 's3', title: 'Track CPL convergence by region', subtitle: 'STRATIS MONITORS ADOPTION', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-bronco-bc-regional', createdAt: at(0, '06:22:00'),
    enterprise: 'ford-canada', category: 'tactical-efficiency', scope: 'campaign', scoped: true,
    division: 'tier-2', productLine: 'bronco', campaign: 'ford-bronco-bc-regional',
    channels: ['instagram', 'tiktok', 'google-search'], geos: ['bc'],
    title: 'The BC Rugged-SUV Regional Is Paying Rising TikTok CPMs for Flat Results — the Adventure Audience There Has Shifted, and the Budget Hasn’t',
    summary: 'On the BC adventure flight, TikTok cost-of-reach has climbed three weeks running while leads held flat — we’re paying more for the same result. The adventure-lifestyle audience’s attention in-market has moved toward short-form discovery, but the budget split still mirrors last quarter. Trim the now-overpriced TikTok reach back to its efficient run-rate and redeploy to the intent-search and Instagram placements still beating benchmark.',
    evidence: [
      'BC TikTok cost-of-reach up ~22% over three weeks with leads flat.',
      'Budget split unchanged since the cost climb began.',
      'Local intent-search and Instagram are still beating their benchmark in BC.',
      'STRATIS watches cost vs result by channel weekly — it caught the gap as it opened.',
    ],
    confidence: 0.84,
    impactEstimate: 'Trimming the overpriced TikTok share back to its efficient run-rate stops the rise in cost-per-lead; fully reversible if TikTok pricing normalizes.',
    recommendedAction: 'Reduce TikTok weight to its efficient run-rate and redeploy to BC intent-search + Instagram. STRATIS reverses the move if TikTok pricing comes back down.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Reduce TikTok to its efficient run-rate', subtitle: 'REVERSIBLE', type: 'budget', completed: false },
      { id: 's2', title: 'Redeploy to BC search + Instagram', subtitle: 'STILL BEATING BENCHMARK', type: 'budget', completed: false },
      { id: 's3', title: 'Alert when cost and results drift apart', subtitle: 'STRATIS WATCHES WEEKLY', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-f150-bc-regional', createdAt: at(0, '06:24:00'),
    enterprise: 'ford-canada', category: 'tactical-efficiency', scope: 'campaign', scoped: true,
    division: 'tier-2', productLine: 'f150', campaign: 'ford-f150-bc-regional',
    channels: ['google-search', 'facebook', 'instagram'], geos: ['bc'],
    title: 'The BC Full-Size Truck Regional Has Search Headroom — Cost-per-Lead Stays Flat to ~30% More Spend, and the Cap Is Set Below Profitable Demand',
    summary: 'This campaign’s search line is capped below where it stops being profitable. Marginal cost-per-lead holds flat out to roughly +30% spend before it rises — meaning there’s profitable BC truck demand the cap is leaving on the table. The budget is set on last year’s plan, not on the live marginal curve. Raise the cap to the point where CPL actually starts climbing.',
    evidence: [
      'Marginal CPL stays flat from current spend to ~+30% before rising.',
      'The search cap sits below the point of diminishing returns.',
      'BC truck-intender query volume is unmet at the current cap.',
      'STRATIS reads the marginal curve live; the cap reflects last year’s plan.',
    ],
    confidence: 0.86,
    impactEstimate: 'Raising the cap to the efficient frontier is projected to add ~12% more BC truck leads at a flat cost per lead — profitable volume currently turned away.',
    recommendedAction: 'Lift the BC truck search cap to where marginal CPL begins to rise and hold it there. STRATIS moves the cap with the curve.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Raise the search cap to the frontier', subtitle: 'CAPTURE PROFITABLE DEMAND', type: 'budget', completed: false },
      { id: 's2', title: 'Hold it where marginal CPL rises', subtitle: 'NOT LAST YEAR’S PLAN', type: 'bidding', completed: false },
      { id: 's3', title: 'Move the cap with the curve', subtitle: 'STRATIS WATCHES THE MARGIN', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-lightning-on-regional', createdAt: at(0, '06:26:00'),
    enterprise: 'ford-canada', category: 'national-regional', scope: 'campaign', scoped: true,
    division: 'tier-2', productLine: 'lightning', campaign: 'ford-lightning-on-regional',
    channels: ['google-search', 'instagram', 'facebook', 'spotify'], geos: ['ontario'],
    title: 'The Ontario Electric Pickup Regional Is the Network’s Worst Cost-per-Lead (~$298) — and the Fix Is the BC Playbook, Not More Budget',
    summary: 'This is the anomaly market: at ~$298 the Ontario Electric Pickup regional converts the same nameplate at roughly double BC’s cost. The diagnosis isn’t a weak market — it’s broad prospecting waste and a Spotify line that isn’t converting, while intent-search is under-funded. The same BC recipe that runs at ~$148 applies directly here. This campaign should be the first recipient of the exported playbook.',
    evidence: [
      'Ontario Electric Pickup CPL ~$298 vs ~$148 for the same nameplate in BC.',
      '~40% of the flight sits in broad prospecting that converts well below intent-search.',
      'The Spotify line is the weakest converter in the flight.',
      'STRATIS isolates the waste against the proven BC structure — same nameplate, half the cost.',
    ],
    confidence: 0.88,
    impactEstimate: 'Porting the BC structure (cut broad prospecting, fund intent-search) is projected to bring Ontario CPL toward ~$210–$230 — recovering roughly $0.8M of the flight’s spend efficiency.',
    recommendedAction: 'Cut the broad-prospecting and weak Spotify weight, fund intent-search on the BC pattern, and re-measure CPL weekly. STRATIS tracks the convergence.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Cut broad prospecting + weak Spotify', subtitle: 'WHERE THE $298 COMES FROM', type: 'budget', completed: false },
      { id: 's2', title: 'Fund intent-search on the BC pattern', subtitle: 'THE PROVEN STRUCTURE', type: 'targeting', completed: false },
      { id: 's3', title: 'Re-measure CPL weekly to convergence', subtitle: 'STRATIS MONITORS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-f150-on-regional', createdAt: at(0, '06:28:00'),
    enterprise: 'ford-canada', category: 'tactical-efficiency', scope: 'campaign', scoped: true,
    division: 'tier-2', productLine: 'f150', campaign: 'ford-f150-on-regional',
    channels: ['google-search', 'facebook', 'instagram', 'ttd'], geos: ['ontario'],
    title: 'The Ontario Full-Size Truck Regional Is Overlapping the Dealer Spring Flight on the Same Search Terms — They’re Bidding Each Other Up in the Toronto DMA',
    summary: 'Two ACME flights — this regional and the Tier-3 dealer spring event — are buying the same Ontario truck search terms without coordination, so they’re inflating each other’s CPC in the Toronto DMA. It’s an ACME-vs-ACME auction tax: spend is going up with no incremental demand. De-conflict the keyword and geo overlap so the two flights complement instead of compete.',
    evidence: [
      'The regional and the dealer spring flight overlap on a cluster of Ontario truck terms.',
      'Contested-term CPC runs materially above the flight’s non-contested CPC.',
      'No coordination layer exists between the regional and Tier-3 dealer buys.',
      'STRATIS sees both flights at once — neither buy’s own report shows the self-bidding.',
    ],
    confidence: 0.85,
    impactEstimate: 'De-conflicting the overlap is projected to recover the contested-term CPC premium — roughly $0.5M a year currently lost to ACME bidding against ACME.',
    recommendedAction: 'Split the contested terms and geos between the regional and dealer flights so they complement, not compete. STRATIS flags new overlaps as they form.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Split the contested terms + geos', subtitle: 'STOP ACME-VS-ACME BIDDING', type: 'bidding', completed: false },
      { id: 's2', title: 'Assign roles to each flight', subtitle: 'COMPLEMENT, NOT COMPETE', type: 'targeting', completed: false },
      { id: 's3', title: 'Flag new overlaps continuously', subtitle: 'STRATIS WATCHES BOTH FLIGHTS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-explorer-on-regional', createdAt: at(0, '06:30:00'),
    enterprise: 'ford-canada', category: 'tactical-efficiency', scope: 'campaign', scoped: true,
    division: 'tier-2', productLine: 'explorer', campaign: 'ford-explorer-on-regional',
    channels: ['google-search', 'facebook', 'instagram'], geos: ['ontario'],
    title: 'The Ontario Three-Row Regional Is Funding Facebook Prospecting at the Weakest Return in the Flight — Intent-Search Has Room and Converts ~1.7× Better',
    summary: 'On the Ontario family-SUV flight, broad Facebook prospecting is absorbing the largest budget slice at the lowest conversion, while intent-search — which converts family shoppers ~1.7× better — has clear headroom. The mix is set to reach, not to return. Rebalance from the broad prospecting tail into the search line that’s still on its steep curve.',
    evidence: [
      'Intent-search converts Ontario family shoppers ~1.7× the broad Facebook prospecting line.',
      'Facebook prospecting holds the largest slice at the weakest conversion.',
      'Search has headroom — marginal CPL is still flat at current spend.',
      'STRATIS ranks the flight’s lines by conversion per dollar, not reach.',
    ],
    confidence: 0.85,
    impactEstimate: 'Rebalancing toward intent-search is projected to lift the flight’s family-SUV conversions ~11% at flat spend by moving off the broad prospecting tail.',
    recommendedAction: 'Move budget from broad Facebook prospecting into intent-search and retarget known visitors on social. STRATIS rebalances as efficiency shifts.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Trim broad Facebook prospecting', subtitle: 'WEAKEST RETURN IN THE FLIGHT', type: 'budget', completed: false },
      { id: 's2', title: 'Fund intent-search with headroom', subtitle: 'STILL ON THE STEEP CURVE', type: 'budget', completed: false },
      { id: 's3', title: 'Keep social on retargeting', subtitle: 'WHERE IT STILL WINS', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-f150-ab-regional', createdAt: at(0, '06:32:00'),
    enterprise: 'ford-canada', category: 'national-regional', scope: 'campaign', scoped: true,
    division: 'tier-2', productLine: 'f150', campaign: 'ford-f150-ab-regional',
    channels: ['google-search', 'facebook', 'instagram'], geos: ['alberta'],
    title: 'The Alberta Full-Size Truck Regional Sits Just Above the National Baseline (~$210) — Fleet & Commercial Intent Is Under-Served and Converts Best Here',
    summary: 'Alberta runs close to the Tier-1 baseline, but the flight treats it as a generic truck market. The signal in the data is fleet/commercial: Alberta over-indexes on fleet truck intent, and that segment converts at the best rate in the flight — yet it gets a minority of the budget behind broad retail truck messaging. Tilt the Alberta flight toward the fleet intent it actually over-indexes on.',
    evidence: [
      'Alberta over-indexes on fleet/commercial truck intent vs the national average.',
      'Fleet intent is the best-converting segment in the Alberta flight.',
      'It receives a minority of budget behind broad retail truck creative.',
      'STRATIS reads the regional segment mix — the national plan averages it away.',
    ],
    confidence: 0.84,
    impactEstimate: 'Tilting toward the over-indexed fleet segment is projected to lift Alberta truck conversions ~10% at flat spend by funding the demand the market actually shows.',
    recommendedAction: 'Reweight the Alberta flight toward fleet/commercial intent and creative, trimming broad retail reach. STRATIS keeps scoring the regional segment mix.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Fund the over-indexed fleet segment', subtitle: 'WHERE ALBERTA CONVERTS BEST', type: 'targeting', completed: false },
      { id: 's2', title: 'Trim broad retail truck reach', subtitle: 'MATCH SPEND TO DEMAND', type: 'budget', completed: false },
      { id: 's3', title: 'Re-score the regional segment mix', subtitle: 'STRATIS WATCHES THE TILT', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-bronco-ab-regional', createdAt: at(0, '06:34:00'),
    enterprise: 'ford-canada', category: 'tactical-efficiency', scope: 'campaign', scoped: true,
    division: 'tier-2', productLine: 'bronco', campaign: 'ford-bronco-ab-regional',
    channels: ['instagram', 'tiktok', 'facebook'], geos: ['alberta'],
    title: 'The Alberta Rugged-SUV Regional Is the Smallest-Funded Adventure Flight but Holds the Highest Engagement — It Has Reach Headroom It Isn’t Buying',
    summary: 'This is the lowest-budget adventure flight, yet its social engagement rate is the strongest in the regional set — the Alberta adventure audience is responding, and the flight is simply under-bought. Unique reach is still climbing with spend (no saturation), so added budget here finds new people rather than repeating to the same ones. This is a fund-the-winner call, not a fix.',
    evidence: [
      'Alberta adventure engagement rate is the highest in the regional adventure set.',
      'The flight is the smallest-funded — unique reach is still climbing with spend.',
      'No saturation yet: added budget finds net-new people, not frequency.',
      'STRATIS flags under-funded high-engagement flights the plan overlooks.',
    ],
    confidence: 0.83,
    impactEstimate: 'Funding the under-bought Alberta flight to its reach ceiling is projected to add ~14% net-new adventure reach at an efficient cost while engagement is strong.',
    recommendedAction: 'Raise the Alberta adventure budget toward its reach ceiling while engagement leads, drawing from saturated flights elsewhere. STRATIS watches the reach curve.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Fund the high-engagement Alberta flight', subtitle: 'IT’S UNDER-BOUGHT', type: 'budget', completed: false },
      { id: 's2', title: 'Draw from saturated flights elsewhere', subtitle: 'MOVE TO NET-NEW REACH', type: 'budget', completed: false },
      { id: 's3', title: 'Stop at the reach ceiling', subtitle: 'STRATIS WATCHES THE CURVE', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-f150-qc-cossette', createdAt: at(0, '06:36:00'),
    enterprise: 'ford-canada', category: 'creative-performance', scope: 'campaign', scoped: true,
    division: 'tier-2', productLine: 'f150', campaign: 'ford-f150-qc-cossette',
    channels: ['google-search', 'facebook', 'instagram', 'spotify'], geos: ['quebec'],
    title: 'In Quebec, the Locally-Authored French Truck Creative Is Converting ~1.6× the Adapted National Spot — but the Adapted Version Still Holds Most of the Views',
    summary: 'The Quebec truck flight runs two creative streams: a locally-authored French execution and a translated adaptation of the national spot. On the same conversion metric, the local-original converts ~1.6× the adaptation — Quebec responds to creative built for it, not adapted into it. Yet delivery still defaults to the adapted version. Give the proven local-original the views and brief more in that vein.',
    evidence: [
      'The locally-authored French creative converts ~1.6× the adapted national spot in Quebec.',
      'The adapted version still holds the majority of the flight’s views.',
      'The edge holds across Quebec metros — not a single-market quirk.',
      'STRATIS ranks creative by conversions driven, surfacing the local-vs-adapted gap.',
    ],
    confidence: 0.87,
    impactEstimate: 'Shifting Quebec delivery to the proven local-original lifts the flight’s conversion rate at no production cost and points the agency at what to make more of.',
    recommendedAction: 'Re-weight Quebec delivery to the local-original French creative and brief more locally-authored work. STRATIS holds the creative ranking.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Give the local-original the views', subtitle: 'BUILT FOR QC, NOT ADAPTED', type: 'creative', completed: false },
      { id: 's2', title: 'Shift delivery off the adapted spot', subtitle: 'FREE GAIN — NO NEW SPEND', type: 'creative', completed: false },
      { id: 's3', title: 'Brief more locally-authored work', subtitle: 'PROVEN APPROACH → MORE', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-escape-qc-cossette', createdAt: at(0, '06:38:00'),
    enterprise: 'ford-canada', category: 'national-regional', scope: 'campaign', scoped: true,
    division: 'tier-2', productLine: 'escape-phev', campaign: 'ford-escape-qc-cossette',
    channels: ['google-search', 'facebook', 'instagram'], geos: ['quebec'],
    title: 'Quebec PHEV Demand Is Running Ahead of the Rest of the Country — the Province’s Rebate Stack Makes the Plug-In Hybrid SUV Cheaper There, and This Flight Is Under-Funded for It',
    summary: 'Quebec’s provincial incentive stacks with the federal rebate, so the effective PHEV price is lowest in the country there — and organic plug-in-hybrid search in Quebec is running ahead of the national curve. This Cossette flight is sized to a generic regional plan, not to the strongest PHEV demand in Canada. Fund the affordability message into the province where the math is most favorable.',
    evidence: [
      'Quebec’s rebate stack makes the effective PHEV price the lowest nationally.',
      'Organic Quebec plug-in-hybrid search leads the national curve.',
      'The flight is sized to a generic regional plan, under the live demand.',
      'STRATIS triangulates provincial rebate + search to size the opportunity; correlation, not cause.',
    ],
    confidence: 0.84,
    impactEstimate: 'Funding the affordability message into Quebec’s favorable rebate window is projected to capture ~12% more PHEV intenders at a lower cost per lead while the demand leads.',
    recommendedAction: 'Raise the Quebec PHEV flight’s weight on affordability search and social while the rebate stack and demand lead. STRATIS alerts if either shifts.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Fund Quebec’s favorable PHEV window', subtitle: 'LOWEST EFFECTIVE PRICE NATIONALLY', type: 'budget', completed: false },
      { id: 's2', title: 'Lead with the affordability message', subtitle: 'THE MATH FAVORS QC NOW', type: 'creative', completed: false },
      { id: 's3', title: 'Alert if the rebate or demand shifts', subtitle: 'STRATIS WATCHES QC', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-f150-at-regional', createdAt: at(0, '06:40:00'),
    enterprise: 'ford-canada', category: 'tactical-efficiency', scope: 'campaign', scoped: true,
    division: 'tier-2', productLine: 'f150', campaign: 'ford-f150-at-regional',
    channels: ['google-search', 'facebook', 'instagram'], geos: ['atlantic'],
    title: 'The Atlantic Full-Size Truck Regional Runs the Smallest Budget at a Below-Baseline Cost-per-Lead — It’s Efficient and Starved, Not Inefficient',
    summary: 'Atlantic is the smallest regional truck flight, and it’s quietly one of the most efficient — converting below the Tier-1 CPL baseline despite the modest budget. The constraint here isn’t performance, it’s funding: the flight hits its reach ceiling early and then has nowhere to grow. Where other flights are saturated, this one has efficient headroom that the plan isn’t buying.',
    evidence: [
      'Atlantic truck CPL runs below the Tier-1 baseline despite the smallest budget.',
      'The flight reaches its budget ceiling early — efficient, but capped.',
      'Unique reach is still climbing where the flight runs out of money.',
      'STRATIS flags efficient-but-starved flights the plan under-funds.',
    ],
    confidence: 0.83,
    impactEstimate: 'Adding efficient budget to the under-funded Atlantic flight is projected to capture ~10% more truck leads below the national CPL — drawn from saturated flights elsewhere.',
    recommendedAction: 'Lift the Atlantic truck budget toward its reach ceiling, funded from saturated flights, while CPL stays below baseline. STRATIS watches the ceiling.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Fund the efficient Atlantic flight', subtitle: 'STARVED, NOT INEFFICIENT', type: 'budget', completed: false },
      { id: 's2', title: 'Draw from saturated flights', subtitle: 'MOVE TO THE BETTER MARGIN', type: 'budget', completed: false },
      { id: 's3', title: 'Stop at the reach ceiling', subtitle: 'STRATIS WATCHES THE CURVE', type: 'scheduling', completed: false },
    ],
  },

  // ──────────────────────── TIER 3 — DEALER NETWORK ────────────────────────
  {
    id: 'ins-auto-cmp-ford-dealer-spring-sales', createdAt: at(0, '06:42:00'),
    enterprise: 'ford-canada', category: 'tactical-efficiency', scope: 'campaign', scoped: true,
    division: 'tier-3', productLine: 'f150', campaign: 'ford-dealer-spring-sales',
    channels: ['facebook', 'instagram', 'google-search'], geos: ['ontario', 'alberta', 'bc', 'quebec', 'atlantic'],
    title: 'The Dealer Spring Sales Event Runs the Same Creative in Five Provinces at One National Cadence — but Spring Demand Peaks Weeks Apart by Region',
    summary: 'The aggregate dealer spring event flights a single creative and pacing plan across all five provinces, but truck-buying spring demand doesn’t arrive on the same date — it peaks weeks apart from BC to Atlantic. Even national pacing over-spends where demand hasn’t arrived and under-spends where it’s already here. Stagger the flight to each region’s demand curve instead of one national calendar.',
    evidence: [
      'Regional spring truck demand peaks weeks apart across the five provinces.',
      'The event runs one creative + one national pacing plan across all of them.',
      'Even pacing over-delivers in pre-peak regions and under-delivers in peaking ones.',
      'STRATIS reads each region’s demand curve — the national calendar averages them.',
    ],
    confidence: 0.85,
    impactEstimate: 'Staggering the event to each region’s demand curve is projected to lift event leads ~9% at flat spend by putting weight where demand has actually arrived.',
    recommendedAction: 'Phase the dealer spring flight to each province’s demand peak rather than one national cadence. STRATIS sequences the regional windows.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Stagger pacing to regional demand peaks', subtitle: 'NOT ONE NATIONAL CALENDAR', type: 'scheduling', completed: false },
      { id: 's2', title: 'Shift weight to the peaking regions', subtitle: 'WHERE DEMAND HAS ARRIVED', type: 'budget', completed: false },
      { id: 's3', title: 'Sequence the regional windows', subtitle: 'STRATIS TIMES EACH PEAK', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-dealer-lightning-leads', createdAt: at(0, '06:44:00'),
    enterprise: 'ford-canada', category: 'audience-overlap', scope: 'campaign', scoped: true,
    division: 'tier-3', productLine: 'lightning', campaign: 'ford-dealer-lightning-leads',
    channels: ['facebook', 'instagram', 'google-search'], geos: ['ontario', 'alberta', 'bc', 'quebec'],
    title: 'The Dealer Electric-Pickup Lead-Gen Flight Is Buying the Same EV-Considerer the National Launch Hero Already Reaches Heavily — Stacked, That Buyer Is Over-Exposed and Lead Quality Is Slipping',
    summary: 'The Tier-3 dealer EV lead-gen flight and the national Electric Pickup launch hero buy the same EV-considerer audience without a shared cap, so that prospect is seeing stacked ACME electric-pickup messaging well past the effective frequency — and the dealer flight’s lead quality is softening as it re-touches already-saturated people instead of finding new in-market ones. Cap across the two flights and point dealer dollars at fresh local intent.',
    evidence: [
      'The dealer flight and national launch hero buy the same EV-considerer with no shared cap.',
      'Stacked exposure on that buyer is past the effective frequency ceiling.',
      'Dealer lead quality is slipping as it re-touches saturated prospects.',
      'STRATIS dedupes across the national and dealer flights — neither buy sees the stack.',
    ],
    confidence: 0.86,
    impactEstimate: 'Capping across the two flights and redirecting dealer spend to fresh local intent is projected to lift dealer lead quality and recover ~13% of wasted re-touch spend.',
    recommendedAction: 'Set a shared cap across the national and dealer EV flights and point dealer budget at net-new local intent. STRATIS enforces the combined cap.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Cap across national + dealer EV flights', subtitle: 'STOP STACKING ON ONE BUYER', type: 'bidding', completed: false },
      { id: 's2', title: 'Point dealer spend at fresh local intent', subtitle: 'FIND NEW IN-MARKET PEOPLE', type: 'targeting', completed: false },
      { id: 's3', title: 'Enforce the combined cap', subtitle: 'STRATIS DEDUPES THE FLIGHTS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-cmp-ford-dealer-suv-shoppers', createdAt: at(0, '06:46:00'),
    enterprise: 'ford-canada', category: 'tactical-efficiency', scope: 'campaign', scoped: true,
    division: 'tier-3', productLine: 'explorer', campaign: 'ford-dealer-suv-shoppers',
    channels: ['facebook', 'instagram', 'google-search'], geos: ['ontario', 'alberta', 'bc'],
    title: 'The Dealer SUV Lead-Gen Flight Is Slow to Follow Up — Leads Contacted Within Five Minutes Convert Far Better, and Most Dealer Leads Wait Hours',
    summary: 'The aggregate dealer SUV flight generates leads efficiently, but the value leaks after the click: leads contacted within five minutes convert dramatically better than the network average, and most dealer leads in this flight wait hours for a first touch. The media is doing its job; the speed-to-lead handoff isn’t. The biggest gain here isn’t more spend — it’s closing the response-time gap.',
    evidence: [
      'Leads contacted <5 minutes convert far above the dealer-network average.',
      'Most leads from this flight wait hours for a first dealer touch.',
      'The drop-off is in handoff speed, not lead volume or media efficiency.',
      'STRATIS joins media leads to dealer response time — neither system shows the gap alone.',
    ],
    confidence: 0.85,
    impactEstimate: 'Closing the speed-to-lead gap is projected to lift the flight’s lead-to-appointment rate ~18% with no added media spend — pure conversion of leads already paid for.',
    recommendedAction: 'Route this flight’s leads to a <5-minute response SLA and flag slow dealers. STRATIS monitors speed-to-lead against conversion.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Set a <5-minute speed-to-lead SLA', subtitle: 'WHERE CONVERSION IS WON', type: 'scheduling', completed: false },
      { id: 's2', title: 'Flag the slowest-responding dealers', subtitle: 'CLOSE THE HANDOFF GAP', type: 'targeting', completed: false },
      { id: 's3', title: 'Monitor speed-to-lead vs conversion', subtitle: 'STRATIS WATCHES THE HANDOFF', type: 'scheduling', completed: false },
    ],
  },
];

// ───────────────────────────── Visuals ─────────────────────────────
export const AUTO_CAMPAIGN_VISUALS: Record<string, InsightVisual> = {
  'ins-auto-cmp-ford-lightning-launch-hero': {
    kind: 'line', xKey: 'week', series: ['ctv', 'search'],
    config: { ctv: { label: 'CTV — conv. per +$100K', color: RED }, search: { label: 'Search — conv. per +$100K', color: TEAL } },
    refLines: [{ axis: 'x', value: 'Launch', label: 'Hero launch', color: GOLD }],
    data: [
      { week: 'Pre', ctv: 20, search: 9 }, { week: 'Launch', ctv: 18, search: 16 },
      { week: '+1', ctv: 11, search: 22 }, { week: '+2', ctv: 6, search: 24 }, { week: '+3', ctv: 5, search: 23 },
    ],
    caption: 'Post-launch, CTV flattens while search intent the launch created keeps converting',
  },
  'ins-auto-cmp-ford-f150-built-tough': {
    kind: 'line', xKey: 'views', series: ['hero', 'fresh'],
    config: { hero: { label: 'Built-Tough hero', color: RED }, fresh: { label: 'Capability cut', color: TEAL } },
    data: [
      { views: '1–3', hero: 100, fresh: 104 }, { views: '4–6', hero: 88, fresh: 103 },
      { views: '7–9', hero: 72, fresh: 101 }, { views: '10+', hero: 61, fresh: 99 },
    ],
    caption: 'The hero collapses with repeat views while the fresher cut holds — wear-out, not delivery',
  },
  'ins-auto-cmp-ford-mach-e-defense': {
    kind: 'line', xKey: 'week', series: ['us', 'rival'],
    config: { us: { label: 'Our comparison-term win rate', color: TEAL }, rival: { label: 'Rival bid pressure', color: RED } },
    data: [
      { week: 'W1', us: 72, rival: 100 }, { week: 'W2', us: 66, rival: 118 },
      { week: 'W3', us: 60, rival: 131 }, { week: 'W4', us: 57, rival: 140 },
    ],
    caption: 'The compact-EV rival is taking the comparison auction we depend on',
  },
  'ins-auto-cmp-ford-bronco-adventure-national': {
    kind: 'bar', xKey: 'ad', series: ['rate'], perBarColor: true,
    config: { rate: { label: 'Conversions driven (index)', color: TEAL } },
    data: [
      { ad: 'CTV hero', rate: 100, fill: MUTED }, { ad: 'Vertical trail cut', rate: 152, fill: TEAL }, { ad: 'Static social', rate: 84, fill: MUTED },
    ],
    legend: [{ label: 'Winner — only ~13% of views', color: TEAL }, { label: 'Hero — most of the views', color: MUTED }],
    caption: 'The vertical trail cut wins ~1.5× on social but is starved of delivery',
  },
  'ins-auto-cmp-ford-explorer-family': {
    kind: 'pie', nameKey: 'seg', valueKey: 'share', series: ['share'],
    config: { crossshop: { label: 'Cross-shopping the import three-row', color: RED }, other: { label: 'Not cross-shopping', color: MUTED } },
    legend: [{ label: 'Cross-shopping the import three-row', color: RED }, { label: 'Not cross-shopping', color: MUTED }],
    data: [{ seg: 'crossshop', share: 33, fill: RED }, { seg: 'other', share: 67, fill: MUTED }],
    caption: '~1 in 3 reached family shoppers cross-shop the import three-row — meet them there',
  },
  'ins-auto-cmp-ford-escape-phev-izev': {
    kind: 'line', xKey: 'day', series: ['gas', 'search'],
    yTitle: 'Gas ¢/L · search index',
    config: { gas: { label: 'Gas price ($/L, ×100)', color: GOLD }, search: { label: 'Plug-in-hybrid search', color: TEAL } },
    refLines: [{ axis: 'y', value: 165, label: '$1.65 threshold', color: GRID }],
    data: [
      { day: 'D1', gas: 164, search: 100 }, { day: 'D6', gas: 167, search: 110 },
      { day: 'D11', gas: 170, search: 124 }, { day: 'D16', gas: 171, search: 136 },
    ],
    caption: 'Gas above threshold + the rebate are pulling PHEV search up — fund the window',
  },
  'ins-auto-cmp-ford-transit-fleet': {
    kind: 'bar', xKey: 'channel', series: ['eff'], perBarColor: true,
    config: { eff: { label: 'Demos per dollar (index)', color: TEAL } },
    data: [
      { channel: 'LinkedIn', eff: 210, fill: TEAL }, { channel: 'Search', eff: 128, fill: BLUE }, { channel: 'Programmatic', eff: 100, fill: RED },
    ],
    legend: [{ label: 'Books the most fleet demos', color: TEAL }, { label: 'Cheap CPM, fewest demos', color: RED }],
    caption: 'LinkedIn books fleet demos at ~2.1× programmatic — but holds a third of budget',
  },
  'ins-auto-cmp-ford-edge-mature': {
    kind: 'line', xKey: 'month', series: ['demand'],
    config: { demand: { label: 'Nameplate demand (index)', color: RED } },
    data: [
      { month: 'Jan', demand: 100 }, { month: 'Feb', demand: 96 }, { month: 'Mar', demand: 91 },
      { month: 'Apr', demand: 87 }, { month: 'May', demand: 83 },
    ],
    caption: 'Demand is declining — harvest to an intent-only floor, don’t fund awareness',
  },
  'ins-auto-cmp-ford-brand-q2': {
    kind: 'bar', xKey: 'source', series: ['freq'], perBarColor: true,
    config: { freq: { label: 'Ads seen per week', color: TEAL } },
    refLines: [{ axis: 'y', value: 11, label: 'Effective max ~11', color: RED }],
    data: [
      { source: 'Master brand', freq: 7, fill: MUTED }, { source: 'Nameplate flights', freq: 14, fill: MUTED }, { source: 'Combined', freq: 21, fill: RED },
    ],
    caption: 'Stacked on the nameplate flights, the master brand pushes the truck-intender to ~21×/week',
  },
  'ins-auto-cmp-ford-lightning-bc-regional': {
    kind: 'bar', xKey: 'region', series: ['cpl'], perBarColor: true,
    config: { cpl: { label: 'Cost per lead ($)', color: TEAL } },
    refLines: [{ axis: 'y', value: 218, label: 'Tier 1 baseline $218', color: GRID }],
    data: [
      { region: 'BC', cpl: 148, fill: TEAL }, { region: 'AB', cpl: 205, fill: MUTED }, { region: 'AT', cpl: 210, fill: MUTED }, { region: 'ON', cpl: 298, fill: RED },
    ],
    caption: 'BC runs the best CPL in the country (~$148) — its playbook is unused elsewhere',
  },
  'ins-auto-cmp-ford-bronco-bc-regional': {
    kind: 'line', xKey: 'week', series: ['cost', 'leads'],
    config: { cost: { label: 'TikTok cost of reach', color: RED }, leads: { label: 'Leads', color: TEAL } },
    data: [
      { week: 'W1', cost: 100, leads: 100 }, { week: 'W2', cost: 109, leads: 101 },
      { week: 'W3', cost: 117, leads: 99 }, { week: 'W4', cost: 122, leads: 100 },
    ],
    caption: 'BC TikTok got ~22% pricier while leads held flat — trim and redeploy',
  },
  'ins-auto-cmp-ford-f150-bc-regional': {
    kind: 'line', xKey: 'spend', series: ['cpl'],
    xTitle: 'BC truck search spend (indexed)', yTitle: 'Marginal CPL ($)',
    config: { cpl: { label: 'Marginal CPL', color: TEAL } },
    refLines: [{ axis: 'x', value: 100, label: 'Current cap', color: RED }],
    data: [
      { spend: 70, cpl: 142 }, { spend: 85, cpl: 143 }, { spend: 100, cpl: 144 },
      { spend: 115, cpl: 146 }, { spend: 130, cpl: 159 }, { spend: 145, cpl: 178 },
    ],
    caption: 'CPL stays flat to ~+30% — the cap sits below profitable BC truck demand',
  },
  'ins-auto-cmp-ford-lightning-on-regional': {
    kind: 'bar', xKey: 'market', series: ['cpl'], perBarColor: true,
    config: { cpl: { label: 'Cost per lead ($)', color: RED } },
    refLines: [{ axis: 'y', value: 148, label: 'BC proven $148', color: TEAL }],
    data: [
      { market: 'Ontario (now)', cpl: 298, fill: RED }, { market: 'Target (BC playbook)', cpl: 220, fill: GOLD }, { market: 'BC', cpl: 148, fill: TEAL },
    ],
    caption: 'Ontario is the $298 anomaly — the BC structure is the fix, not more budget',
  },
  'ins-auto-cmp-ford-f150-on-regional': {
    kind: 'bar', xKey: 'type', series: ['cpc'], perBarColor: true,
    config: { cpc: { label: 'Average CPC ($)', color: TEAL } },
    data: [
      { type: 'Non-contested', cpc: 3.2, fill: MUTED }, { type: 'Regional vs dealer (contested)', cpc: 5.1, fill: RED },
    ],
    caption: 'The regional and dealer flights bid each other up on the same Toronto-DMA terms',
  },
  'ins-auto-cmp-ford-explorer-on-regional': {
    kind: 'bar', xKey: 'line', series: ['conv'], perBarColor: true,
    config: { conv: { label: 'Conversion per dollar (index)', color: TEAL } },
    data: [
      { line: 'Intent search', conv: 170, fill: TEAL }, { line: 'Retargeting', conv: 120, fill: BLUE }, { line: 'Broad FB prospecting', conv: 100, fill: RED },
    ],
    caption: 'Intent-search converts ~1.7× broad prospecting — which holds the budget',
  },
  'ins-auto-cmp-ford-f150-ab-regional': {
    kind: 'bar', xKey: 'segment', series: ['idx'], perBarColor: true,
    config: { idx: { label: 'AB index vs national (100)', color: TEAL } },
    refLines: [{ axis: 'y', value: 100, label: 'National avg', color: GRID }],
    data: [
      { segment: 'Fleet/commercial', idx: 142, fill: TEAL }, { segment: 'Retail truck', idx: 96, fill: MUTED },
    ],
    caption: 'Alberta over-indexes on fleet intent — and it converts best; tilt the flight to it',
  },
  'ins-auto-cmp-ford-bronco-ab-regional': {
    kind: 'scatter', xKey: 'budget', series: ['engagement'],
    xName: 'Budget (index)', yName: 'Engagement rate (index)',
    config: { engagement: { label: 'Regional adventure flight', color: PURPLE } },
    data: [
      { budget: 38, engagement: 138 }, { budget: 64, engagement: 112 }, { budget: 70, engagement: 104 },
      { budget: 95, engagement: 96 }, { budget: 100, engagement: 91 },
    ],
    caption: 'Smallest-funded Alberta flight, highest engagement — reach headroom it isn’t buying',
  },
  'ins-auto-cmp-ford-f150-qc-cossette': {
    kind: 'bar', xKey: 'creative', series: ['rate'], perBarColor: true,
    config: { rate: { label: 'Conversion (index)', color: TEAL } },
    data: [
      { creative: 'Local-original FR', rate: 160, fill: TEAL }, { creative: 'Adapted national', rate: 100, fill: MUTED },
    ],
    legend: [{ label: 'Built for QC — proven 1.6×', color: TEAL }, { label: 'Adapted — holds most views', color: MUTED }],
    caption: 'The locally-authored French creative converts ~1.6× the adapted spot — give it the views',
  },
  'ins-auto-cmp-ford-escape-qc-cossette': {
    kind: 'line', xKey: 'week', series: ['qc', 'national'],
    config: { qc: { label: 'Quebec PHEV search', color: TEAL }, national: { label: 'National PHEV search', color: MUTED } },
    data: [
      { week: 'W1', qc: 118, national: 100 }, { week: 'W2', qc: 131, national: 104 },
      { week: 'W3', qc: 149, national: 108 }, { week: 'W4', qc: 162, national: 110 },
    ],
    caption: 'Quebec PHEV demand leads the country — the rebate stack makes it cheapest there',
  },
  'ins-auto-cmp-ford-f150-at-regional': {
    kind: 'bar', xKey: 'flight', series: ['cpl'], perBarColor: true,
    config: { cpl: { label: 'Cost per lead ($)', color: TEAL } },
    refLines: [{ axis: 'y', value: 218, label: 'Tier 1 baseline $218', color: GRID }],
    data: [
      { flight: 'Atlantic truck', cpl: 196, fill: TEAL }, { flight: 'Tier 1 baseline', cpl: 218, fill: MUTED },
    ],
    caption: 'Atlantic converts below baseline on the smallest budget — efficient and starved',
  },
  'ins-auto-cmp-ford-dealer-spring-sales': {
    kind: 'line', xKey: 'week', series: ['bc', 'on', 'at'],
    config: { bc: { label: 'BC demand', color: TEAL }, on: { label: 'Ontario demand', color: PURPLE }, at: { label: 'Atlantic demand', color: GOLD } },
    data: [
      { week: 'W1', bc: 132, on: 104, at: 88 }, { week: 'W3', bc: 121, on: 124, at: 99 },
      { week: 'W5', bc: 102, on: 131, at: 118 }, { week: 'W7', bc: 90, on: 116, at: 129 },
    ],
    caption: 'Spring truck demand peaks weeks apart by region — one national cadence misses each',
  },
  'ins-auto-cmp-ford-dealer-lightning-leads': {
    kind: 'bar', xKey: 'source', series: ['freq'], perBarColor: true,
    config: { freq: { label: 'EV-considerer exposures/week', color: TEAL } },
    refLines: [{ axis: 'y', value: 10, label: 'Effective max ~10', color: RED }],
    data: [
      { source: 'National launch', freq: 12, fill: MUTED }, { source: 'Dealer lead-gen', freq: 9, fill: MUTED }, { source: 'Combined', freq: 21, fill: RED },
    ],
    caption: 'Dealer + national stack on the same EV-considerer — over-exposed, lead quality slipping',
  },
  'ins-auto-cmp-ford-dealer-suv-shoppers': {
    kind: 'bar', xKey: 'response', series: ['conv'], perBarColor: true,
    config: { conv: { label: 'Lead→appointment rate (index)', color: TEAL } },
    data: [
      { response: '<5 min', conv: 184, fill: TEAL }, { response: '<1 hr', conv: 116, fill: BLUE }, { response: 'Hours+', conv: 100, fill: RED },
    ],
    caption: 'Leads contacted <5 min convert far better — most dealer leads wait hours',
  },
};
