// ===========================================================================
// ACME Automotive — FILTER-SCOPED signals: REGION + CHANNEL
//
// These insights are not part of the holistic "brand view". Each carries
// `scoped: true` and a region (geos) or channel scope, so it surfaces on the
// Signals page only when that region/channel is selected in the filter layer.
// Spread into the master arrays in mock-data.ts / insight-visuals.ts.
// ===========================================================================
import type { Insight } from '@/types';
import { type InsightVisual, TEAL, RED, BLUE, PURPLE, GOLD, MUTED, GRID } from './insight-visual-types';
import { at } from './clients/_shared';

export const AUTO_CONTEXT_INSIGHTS: Insight[] = [
  // ───────────────────────────── REGION-SCOPED ─────────────────────────────
  {
    id: 'ins-auto-geo-national', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '06:30:00'), category: 'national-regional', scope: 'division', division: 'tier-1',
    geos: ['national'], channels: ['ctv', 'ttd', 'google-search', 'ooh'],
    title: 'National Spend Is Pacing to Population, Not to Where It Converts — Four Provinces Are Carrying Budget That Three Others Would Turn Into ~11% More Leads',
    summary: 'Rolled up to the national plan, the budget split tracks population and last year’s buy, not where media actually converts today. Three provinces are converting well above the national line while drawing less than their share of weight; four are funded ahead of the demand they return. A great planner re-weights the national map once a quarter; STRATIS scores every province on what media returns and keeps the national rollup aligned to it continuously.',
    evidence: [
      'Top three converting provinces draw ~32% less weight than their conversion share warrants.',
      'The national plan still paces to population and the prior-year buy, not current conversion.',
      'Re-weighting is a pure reallocation — no incremental national budget required.',
      'STRATIS scores each province on returned media value and flags drift as it opens.',
    ],
    confidence: 0.87,
    impactEstimate: 'Re-weighting the national map toward converting provinces is projected to lift total leads ~11% at flat national spend, by moving weight off the weakest markets.',
    recommendedAction: 'Re-pace the national plan to provincial conversion rather than population; pull from over-funded provinces into the under-funded converters. STRATIS keeps the rollup aligned as provinces move.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Re-weight the national plan to provincial conversion', subtitle: 'STOP PACING TO POPULATION', type: 'budget', completed: false },
      { id: 's2', title: 'Fund the three over-converting, under-weighted provinces', subtitle: 'MATCH SPEND TO RETURN', type: 'budget', completed: false },
      { id: 's3', title: 'Re-score every province continuously', subtitle: 'KEEP THE MAP AND THE PLAN ALIGNED', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-auto-geo-bc', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '06:33:00'), category: 'national-regional', scope: 'division', division: 'tier-2',
    geos: ['bc'], channels: ['google-search', 'instagram', 'facebook'],
    title: 'BC Is Running the Cheapest Lead in the Country at ~$148 — Half the Regional Average — and Nobody Else Has Copied What It Does Differently',
    summary: 'BC’s regional program converts a lead at about $148 — roughly a third under the Tier-1 baseline and the best in the network — and it isn’t luck. It runs a tight search-plus-social motion against in-market truck and EV intenders with disciplined creative rotation, while the other regions still spread budget across broader, pricier reach. The BC playbook is a proven, documented template; the value left on the table is that four other regions haven’t adopted it.',
    evidence: [
      'BC cost-per-lead ~$148 vs a ~$218 Tier-1 baseline and ~$298 in the weakest region.',
      'BC concentrates on high-intent search + social against in-market intenders, not broad reach.',
      'Creative is rotated on a fixed cadence in BC; other regions let it run to fatigue.',
      'STRATIS has the BC motion documented as a portable template ready to cascade.',
    ],
    confidence: 0.9,
    impactEstimate: 'Cascading the BC playbook to the other four regions is projected to pull regional cost-per-lead toward ~$170 network-wide — double-digit efficiency on the largest pool of regional spend.',
    recommendedAction: 'Promote the BC motion to a network template and cascade it region by region. STRATIS tracks adoption and holds each region against the BC benchmark.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Package the BC motion as the regional template', subtitle: 'PROVEN AT ~$148 CPL', type: 'creative', completed: false },
      { id: 's2', title: 'Cascade it to the four trailing regions', subtitle: 'COPY THE WINNER', type: 'targeting', completed: false },
      { id: 's3', title: 'Hold every region to the BC benchmark', subtitle: 'STRATIS TRACKS ADOPTION', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-geo-alberta', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '06:36:00'), category: 'national-regional', scope: 'division', division: 'tier-2',
    geos: ['alberta'], channels: ['google-search', 'facebook', 'instagram'],
    title: 'Alberta Over-Indexes on Full-Size Truck and Fleet Demand — but the Regional Mix Is Built for Passenger SUVs, Leaving the Province’s Strongest Segment Under-Funded',
    summary: 'Alberta’s in-market demand skews hard to full-size trucks, commercial vans, and fleet buyers — the segments where the province out-converts the national average — yet the regional budget is split as if it were a passenger-SUV market. The strongest, cheapest-converting demand in the province is the least funded. Tilting the Alberta mix toward truck and fleet intent, where the conversion is already proven, lifts results without new budget.',
    evidence: [
      'Alberta full-size truck + fleet intent converts ~1.4× the national average for those segments.',
      'Regional budget weights passenger SUVs in line with the national split, not Alberta demand.',
      'Fleet/commercial search in-province is under-served relative to its conversion.',
      'STRATIS reads provincial segment demand, not the national template.',
    ],
    confidence: 0.85,
    impactEstimate: 'Re-tilting the Alberta mix toward truck/fleet intent is projected to lift provincial leads ~9% at flat spend by funding the segment that already converts best there.',
    recommendedAction: 'Re-weight Alberta toward full-size truck and fleet/commercial intent and trim the over-funded passenger-SUV reach. STRATIS keeps the provincial mix matched to provincial demand.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Tilt Alberta toward truck + fleet intent', subtitle: 'FUND THE PROVINCE’S STRONGEST SEGMENT', type: 'targeting', completed: false },
      { id: 's2', title: 'Trim the passenger-SUV reach tail', subtitle: 'IT UNDER-CONVERTS HERE', type: 'budget', completed: false },
      { id: 's3', title: 'Match the provincial mix to provincial demand', subtitle: 'NOT THE NATIONAL TEMPLATE', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-auto-geo-ontario', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '06:39:00'), category: 'national-regional', scope: 'division', division: 'tier-2',
    geos: ['ontario'], channels: ['google-search', 'facebook', 'instagram', 'ttd'],
    title: 'Ontario Holds the Biggest Regional Budget but the Worst Lead Cost in the Country at ~$298 — the Money Is Going In, the Efficiency Isn’t Coming Out',
    summary: 'Ontario carries the largest regional budget yet returns the most expensive lead in the network at about $298 — roughly double BC. The gap isn’t demand; it’s execution: broad, overlapping reach across agencies, creative left to fatigue, and almost no high-intent search discipline. This is the single biggest efficiency opportunity in the portfolio because it’s the largest budget sitting on the weakest motion. Porting the proven BC playbook here moves the most money the furthest.',
    evidence: [
      'Ontario cost-per-lead ~$298 — the network’s worst — on the network’s largest regional budget.',
      'Reach overlaps across agencies; high-intent search is under-weighted vs broad social.',
      'Creative runs past its refresh window in-market, dragging response.',
      'STRATIS flags Ontario as the highest-$ efficiency recovery in the portfolio.',
    ],
    confidence: 0.88,
    impactEstimate: 'Bringing Ontario even halfway to the BC benchmark is projected to recover ~$3.1M of efficiency a year — the largest single reallocation opportunity in the automotive plan.',
    recommendedAction: 'Restructure Ontario onto the BC motion: consolidate overlapping reach, weight high-intent search, and enforce creative refresh. STRATIS holds Ontario against the benchmark and tracks the recovery.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Port the BC playbook into Ontario', subtitle: 'BIGGEST BUDGET, WEAKEST MOTION', type: 'budget', completed: false },
      { id: 's2', title: 'Consolidate overlapping cross-agency reach', subtitle: 'STOP PAYING TWICE FOR THE SAME PERSON', type: 'bidding', completed: false },
      { id: 's3', title: 'Enforce creative refresh + search discipline', subtitle: 'STRATIS TRACKS THE RECOVERY', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-auto-geo-quebec', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '06:42:00'), category: 'national-regional', scope: 'division', division: 'tier-2',
    geos: ['quebec'], channels: ['facebook', 'instagram', 'google-search', 'spotify'],
    title: 'Quebec’s Locally-Built French Creative Is Converting ~2.3× the Adapted National Cut — but It Still Holds a Minority of Delivery, and Compliance Is Done Province-by-Province',
    summary: 'In Quebec, the French creative built locally by the regional partner converts at roughly 2.3× the rate of the translated national cut running beside it — the language and cultural fit are doing real work — yet delivery still defaults to the adapted national asset. Separately, OQLF French-language compliance is handled creative-by-creative instead of from one approved template, which is slow and duplicative. Give the proven local creative the delivery, and run compliance from one template, and Quebec gets both lift and lower overhead.',
    evidence: [
      'Locally-built French creative converts ~2.3× the translated national cut on the same metric.',
      'Delivery still defaults to the adapted national asset; the local winner is under-shown.',
      'OQLF compliance is handled per-creative, not from one approved template.',
      'STRATIS ranks creative on conversions driven and flags the delivery default.',
    ],
    confidence: 0.86,
    impactEstimate: 'Shifting delivery to the proven local creative and centralizing OQLF compliance lifts Quebec conversion at no production cost and removes duplicate compliance overhead.',
    recommendedAction: 'Give the locally-built French creative the majority of Quebec delivery and run OQLF compliance from one approved template. STRATIS keeps ranking creative by conversions driven.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Shift Quebec delivery to the local French winner', subtitle: 'PROVEN ~2.3× ON THE SAME METRIC', type: 'creative', completed: false },
      { id: 's2', title: 'Run OQLF compliance from one template', subtitle: 'NOT CREATIVE-BY-CREATIVE', type: 'creative', completed: false },
      { id: 's3', title: 'Rank Quebec creative by conversions driven', subtitle: 'DON’T LET DELIVERY DEFAULT BACK', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-auto-geo-atlantic', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '06:45:00'), category: 'national-regional', scope: 'division', division: 'tier-2',
    geos: ['atlantic'], channels: ['facebook', 'google-search', 'ctv'],
    title: 'Atlantic Has Already Reached Almost Everyone It Can — the Last Slice of Its Budget Is Buying Repeat Views, Not New Shoppers',
    summary: 'Atlantic is a smaller market, and the regional plan has now delivered to nearly everyone reachable in the in-market audience. Each additional dollar there is adding frequency to people already reached rather than finding new shoppers — the same diminishing-returns trap as any saturated channel, just at the province level. Capping Atlantic at its reach ceiling and moving the overflow to provinces with headroom converts wasted repeat views into net-new reach.',
    evidence: [
      'Atlantic unique reach in the in-market audience has flattened; added spend adds frequency, not people.',
      'Other provinces still have net-new reach at a similar cost per person.',
      'This caps the overflow — Atlantic stays funded to its ceiling, it isn’t cut.',
      'STRATIS separates “out of new people” from “inefficient” — different problems, different moves.',
    ],
    confidence: 0.84,
    impactEstimate: 'Capping Atlantic at its reach ceiling and redeploying the overflow lifts net-new shoppers reached portfolio-wide ~6% at the same total spend.',
    recommendedAction: 'Cap Atlantic where its unique reach flattens and move the overflow to provinces with headroom. STRATIS watches each province’s reach ceiling and redirects the overflow.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Cap Atlantic at its reach ceiling', subtitle: 'EFFICIENT, BUT OUT OF NEW PEOPLE', type: 'budget', completed: false },
      { id: 's2', title: 'Redeploy the overflow to provinces with headroom', subtitle: 'BUY PEOPLE, NOT FREQUENCY', type: 'budget', completed: false },
      { id: 's3', title: 'Watch each province’s reach ceiling', subtitle: 'REDIRECT THE OVERFLOW', type: 'scheduling', completed: false },
    ],
  },

  // ───────────────────────────── CHANNEL-SCOPED ────────────────────────────
  {
    id: 'ins-auto-ch-ctv', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '06:50:00'), category: 'tactical-efficiency', scope: 'division', division: 'tier-1',
    channels: ['ctv'],
    title: 'Connected TV Has Passed Its Reach Ceiling on the Core Auto Intender — the Top ~16% of CTV Budget Is Adding Frequency, Not New Shoppers',
    summary: 'Across the nameplate portfolio, CTV has now reached the core in-market auto intender often enough that the response curve has gone flat. The last ~16% of CTV spend is producing almost no incremental lift; it’s buying the eleventh impression for someone who was persuaded at the sixth. A great buyer reads that ceiling off the curve once a quarter; STRATIS watches it continuously and calls the week CTV flattens. Move the saturated tail to channels that still convert at the margin.',
    evidence: [
      'CTV marginal lift per added $100K has fallen to near zero on the core intender.',
      'About 16% of CTV budget sits past the point the curve flattens.',
      'Frequency on the reached audience is well above the persuasion ceiling.',
      'STRATIS flags CTV saturation as it happens; a quarterly model books the tail as “working.”',
    ],
    confidence: 0.89,
    impactEstimate: 'Reallocating the saturated ~16% of CTV is projected to recover ~$2.4M into channels still converting — same reach, more conversions, recovered now.',
    recommendedAction: 'Cap CTV at its reach ceiling and redeploy the tail to search and audio that still convert at the margin. STRATIS holds CTV against its own saturation point and rebalances as it moves.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Cap CTV at the point its curve flattens', subtitle: 'THE LAST 16% ADDS FREQUENCY, NOT REACH', type: 'budget', completed: false },
      { id: 's2', title: 'Redeploy the tail to converting channels', subtitle: 'SEARCH + AUDIO STILL CLIMB', type: 'budget', completed: false },
      { id: 's3', title: 'Watch CTV’s saturation point continuously', subtitle: 'REBALANCE AS IT MOVES', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-ch-instagram', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '06:53:00'), category: 'tactical-efficiency', scope: 'division', division: 'tier-1',
    channels: ['instagram'],
    title: 'Instagram CPM Has Climbed Three Weeks Straight While Cost-per-Lead Held Flat — We’re Paying More for the Same Result and the Budget Hasn’t Reacted',
    summary: 'The price of reaching the audience on Instagram is up about 22% over three weeks, but it isn’t driving any more leads — cost-per-lead is flat. We’re simply paying more for the same outcome, either because the auction tightened or the creative has fatigued. STRATIS watches cost against result by channel every week, so it caught the gap as it opened rather than at the end of a monthly report. The move is a reversible shift away from a channel that quietly got pricier.',
    evidence: [
      'Instagram CPM up ~22% over three weeks; cost-per-lead flat over the same window.',
      'No creative refresh and no audience expansion in the period.',
      'The divergence points to auction inflation or creative fatigue, not better outcomes.',
      'STRATIS tracks cost-vs-result weekly and flagged the gap as it opened.',
    ],
    confidence: 0.83,
    impactEstimate: 'Refreshing creative or trimming the now-overpriced Instagram weight stops the climb in cost-per-lead; fully reversible if CPM normalizes.',
    recommendedAction: 'Refresh the Instagram creative or trim its weight to the efficient run-rate and redeploy; STRATIS reverses the move automatically if CPM comes back down.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Test creative fatigue before anything else', subtitle: 'CPM UP, RESULT FLAT', type: 'creative', completed: false },
      { id: 's2', title: 'Trim Instagram weight to its efficient run-rate', subtitle: 'REVERSIBLE', type: 'budget', completed: false },
      { id: 's3', title: 'Alert when cost and result drift apart', subtitle: 'STRATIS WATCHES WEEKLY', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-ch-facebook', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '06:56:00'), category: 'audience-overlap', scope: 'division', division: 'tier-2',
    channels: ['facebook'],
    title: 'On Facebook, National and Three Regional Campaigns Are All Buying the Same In-Market Shopper — the Overlap Is Inflating CPM and Burning Frequency Nobody Sees',
    summary: 'Facebook is where the national flight and several regional flights quietly collide: each buys the same in-market auto shopper independently, with no shared cap, so they bid against each other and stack frequency on one person. Each campaign’s own report looks fine — the pile-up only appears when you match the audience across all of them. One shared cap on Facebook pulls combined exposure back to the effective range and stops ACME from paying a premium to outbid itself.',
    evidence: [
      'Four ACME campaigns buy the overlapping in-market shopper on Facebook with no shared cap.',
      'Contested-audience CPM runs ~30% above comparable non-contested audiences.',
      'Combined frequency on the shared shopper is roughly double the effective ceiling.',
      'STRATIS matches the audience across campaigns — no single campaign report sees the overlap.',
    ],
    confidence: 0.87,
    impactEstimate: 'A shared Facebook frequency cap removes the self-bidding premium and frees ~$1.6M of duplicated weight to reach shoppers ACME isn’t hitting at all.',
    recommendedAction: 'Set one cross-campaign Facebook frequency cap on the shared audience and reallocate the recovered weight to net-new reach. STRATIS enforces the combined cap continuously.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Set one shared Facebook cap across campaigns', subtitle: 'STOP OUTBIDDING OURSELVES', type: 'bidding', completed: false },
      { id: 's2', title: 'Reallocate freed weight to net-new reach', subtitle: 'BUY SHOPPERS WE’RE MISSING', type: 'budget', completed: false },
      { id: 's3', title: 'Enforce the combined cap continuously', subtitle: 'STRATIS MATCHES ACROSS CAMPAIGNS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-ch-tiktok', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '06:59:00'), category: 'tactical-efficiency', scope: 'division', division: 'tier-2',
    channels: ['tiktok'],
    title: 'TikTok Is Converting Younger Conquest Shoppers at About Two-Thirds the Cost of Meta — and It Still Holds Single-Digit Budget Share',
    summary: 'For the younger conquest and adventure-lifestyle audience, TikTok is now delivering a qualified visit at roughly two-thirds the cost of the same audience on Meta, because that audience’s discovery has shifted there and the auction is less contested. Despite that, TikTok holds only a single-digit share of social budget — the plan hasn’t followed the audience. This is a follow-the-people reallocation, not a bet: the efficiency is already measured.',
    evidence: [
      'TikTok cost per qualified visit ~33% below Meta for the younger conquest audience.',
      'That audience’s discovery has migrated to short-form video; TikTok delivery has headroom.',
      'TikTok holds single-digit social budget share despite the efficiency.',
      'STRATIS compares cost per qualified visit across platforms, not each platform’s own metric.',
    ],
    confidence: 0.85,
    impactEstimate: 'Shifting a slice of younger-audience social budget from Meta to TikTok is projected to cut the blended cost of a qualified visit ~18% and grow conquest reach where it’s cheapest.',
    recommendedAction: 'Move a measured slice of younger-audience prospecting from Meta to TikTok and keep Meta for retargeting known visitors. STRATIS holds the cross-platform efficiency comparison live.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Shift younger-audience prospecting to TikTok', subtitle: 'FOLLOW THE AUDIENCE', type: 'budget', completed: false },
      { id: 's2', title: 'Keep Meta on retargeting known visitors', subtitle: 'WHERE META STILL WINS', type: 'targeting', completed: false },
      { id: 's3', title: 'Compare cost per visit across platforms', subtitle: 'NOT EACH PLATFORM’S OWN METRIC', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-ch-google-search', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '07:02:00'), category: 'tactical-efficiency', scope: 'division', division: 'tier-1',
    channels: ['google-search'],
    title: 'Vehicle Listing & High-Intent Search Convert at ~2.6× the ROAS of Generic Nameplate Terms — Yet Generic Still Holds the Majority of the Search Budget',
    summary: 'Inside Google Search, the formats closest to a ready buyer — vehicle listing ads and high-intent model+trim+“near me” queries — convert at about 2.6× the return of broad generic nameplate terms. But the budget is still weighted to the generic terms because they’re cheap and high-volume, so most of the money chases the least ready searcher. Tilting the search budget toward the high-intent formats lifts conversions without spending more.',
    evidence: [
      'Vehicle-listing + high-intent queries return ~2.6× the ROAS of generic nameplate terms.',
      'Generic terms hold the majority of search budget on volume, not return.',
      'High-intent inventory has headroom — it isn’t capped out.',
      'STRATIS ranks search formats by return per dollar, not by volume or CPC.',
    ],
    confidence: 0.88,
    impactEstimate: 'Re-tilting search toward high-intent formats is projected to lift search-driven leads ~12% at flat spend by moving budget off the lowest-return generic tail.',
    recommendedAction: 'Shift search budget into vehicle-listing and high-intent queries and trim the generic tail. STRATIS keeps ranking formats by return and rebalances as it shifts.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Fund the high-intent search formats', subtitle: 'THE ~2.6× ROAS QUERIES', type: 'budget', completed: false },
      { id: 's2', title: 'Trim the generic-term tail', subtitle: 'VOLUME ISN’T RETURN', type: 'bidding', completed: false },
      { id: 's3', title: 'Rank formats by return per dollar', subtitle: 'NOT BY CPC OR VOLUME', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-auto-ch-ttd', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '07:05:00'), category: 'tactical-efficiency', scope: 'division', division: 'tier-1',
    channels: ['ttd'],
    title: 'A Quarter of Programmatic Display Spend Is Disappearing Into the Open Exchange — Move It to Curated Auto Deals on The Trade Desk for the Same Audience With ~26% Less Waste',
    summary: 'A large share of programmatic display is still running through the open exchange, where about 26% of every dollar is lost to unviewable, low-quality, or off-target inventory — and ads sometimes land next to content the brand shouldn’t be near. Moving that money into curated private deals on The Trade Desk — auto-intender and endemic inventory bought directly — reaches the same shoppers with far less waste and clean adjacency. Same audience, more of the dollar actually working.',
    evidence: [
      'About 26% of open-exchange spend is lost to unviewable, low-quality, or off-target inventory.',
      'Curated Trade Desk deals reach the same auto-intender audience with verified placement.',
      'Open-exchange viewability runs well below the curated-deal benchmark.',
      'STRATIS scores delivered quality, not just the platform’s reported impressions.',
    ],
    confidence: 0.87,
    impactEstimate: 'Moving display from the open exchange into curated deals recovers ~26% of that spend into working impressions — roughly $1.9M a year at the same audience and reach.',
    recommendedAction: 'Shift programmatic display out of the open exchange into curated auto private deals on The Trade Desk. STRATIS keeps scoring delivered quality and flags waste as it reappears.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Move display from open exchange to curated deals', subtitle: 'SAME AUDIENCE, LESS WASTE', type: 'budget', completed: false },
      { id: 's2', title: 'Hold delivery to verified, on-topic inventory', subtitle: 'BRAND-SAFE ADJACENCY', type: 'targeting', completed: false },
      { id: 's3', title: 'Score delivered quality, not reported impressions', subtitle: 'STRATIS WATCHES THE SUPPLY PATH', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-ch-spotify', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '07:08:00'), category: 'audience-overlap', scope: 'division', division: 'tier-1',
    channels: ['spotify'],
    title: 'Audio Is Pulling Real Incremental Lift at the Low End but Tips Into Pure Frequency Past ~8 Plays a Week — and Two Brand Flights Are Pushing the Same Listener Well Past That',
    summary: 'Audio is doing useful work: at low weekly frequency it adds measurable consideration lift among reached listeners. But the lift flattens past roughly eight plays a week, and right now two brand flights are hitting the same listener independently, stacking exposure well past that point. The first few plays persuade; the rest just spend. Capping combined audio frequency holds the incrementality and frees the over-delivered weight.',
    evidence: [
      'Audio consideration lift flattens past ~8 plays/week for the reached listener.',
      'Two brand flights buy the same listener with no shared audio cap.',
      'A meaningful share of audio impressions land above the effective frequency line.',
      'STRATIS matches audio exposure across flights — neither flight sees the stack alone.',
    ],
    confidence: 0.82,
    impactEstimate: 'Capping combined audio at ~8/week holds the incremental lift and frees the over-delivered weight to extend reach — recovering roughly $0.7M of frequency waste.',
    recommendedAction: 'Set one combined audio frequency cap across brand flights and move the recovered weight to under-reached listeners. STRATIS enforces the combined cap continuously.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Set one combined audio cap (~8/week)', subtitle: 'ACROSS FLIGHTS, NOT PER-FLIGHT', type: 'bidding', completed: false },
      { id: 's2', title: 'Move recovered weight to under-reached listeners', subtitle: 'EXTEND REACH', type: 'budget', completed: false },
      { id: 's3', title: 'Enforce the combined audio cap', subtitle: 'STRATIS MATCHES ACROSS FLIGHTS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-auto-ch-linkedin', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '07:11:00'), category: 'tactical-efficiency', scope: 'division', division: 'tier-1',
    channels: ['linkedin'], productLine: 'transit',
    title: 'LinkedIn Is the Cheapest Qualified Fleet Lead We Have for the Commercial Van — but It Holds a Fraction of the Budget the Broader Channels Get',
    summary: 'For the Commercial Van’s fleet and commercial buyer, LinkedIn is converting a qualified lead well below the cost of the broad-reach channels, because it can target the actual decision-maker — fleet managers and operations roles — instead of spraying a consumer audience. Yet the fleet budget still leans on broad channels that reach mostly non-buyers. Concentrating fleet spend where the buyer actually is lifts qualified leads without new budget.',
    evidence: [
      'LinkedIn qualified fleet-lead cost runs well under the broad-channel average for the Commercial Van.',
      'It targets fleet/operations decision-makers directly, not a broad consumer audience.',
      'Fleet budget still weights broad channels that reach mostly non-buyers.',
      'STRATIS ranks fleet channels by qualified-lead cost, not raw reach.',
    ],
    confidence: 0.85,
    impactEstimate: 'Concentrating Commercial-Van fleet budget on LinkedIn is projected to lift qualified fleet leads ~15% at flat spend by moving off broad non-buyer reach.',
    recommendedAction: 'Shift Commercial-Van fleet budget toward LinkedIn decision-maker targeting and trim broad consumer reach. STRATIS keeps ranking fleet channels by qualified-lead cost.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Concentrate fleet budget on LinkedIn', subtitle: 'WHERE THE BUYER ACTUALLY IS', type: 'targeting', completed: false },
      { id: 's2', title: 'Trim broad consumer fleet reach', subtitle: 'IT REACHES MOSTLY NON-BUYERS', type: 'budget', completed: false },
      { id: 's3', title: 'Rank fleet channels by qualified-lead cost', subtitle: 'NOT RAW REACH', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-auto-ch-ooh', scoped: true, enterprise: 'ford-canada',
    createdAt: at(0, '07:14:00'), category: 'tactical-efficiency', scope: 'division', division: 'tier-1',
    channels: ['ooh'],
    title: 'OOH Is Building Brand Where Search Demand Follows — but a Third of the Boards Are in Markets That Already Convert Above the Line, Where the Reminder Adds Little',
    summary: 'Out-of-home is doing its job as a brand-builder: in markets where boards run, branded nameplate search lifts in the following days. But the buy is weighted to high-traffic markets that already convert above the line, where the extra reminder adds little, while several under-developed markets that respond strongly to OOH are under-boarded. Re-weighting the OOH map toward where the brand lift actually moves search lifts the whole funnel without more boards.',
    evidence: [
      'Markets with OOH show a measurable branded-search lift in the days after boards go live.',
      'About a third of boards sit in markets already converting above the national line.',
      'Several OOH-responsive, under-developed markets are under-boarded.',
      'STRATIS ties OOH presence to downstream search lift — a link no OOH report shows alone.',
    ],
    confidence: 0.83,
    impactEstimate: 'Re-weighting OOH toward markets where it actually moves search is projected to lift branded search ~8% at flat OOH spend by moving boards off saturated markets.',
    recommendedAction: 'Shift OOH weight from already-converting markets to under-developed markets that respond to it. STRATIS keeps the OOH-to-search link live and flags drift.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Move boards to OOH-responsive under-developed markets', subtitle: 'WHERE THE REMINDER MOVES SEARCH', type: 'budget', completed: false },
      { id: 's2', title: 'Pull boards from already-converting markets', subtitle: 'THE LIFT IS SMALL THERE', type: 'budget', completed: false },
      { id: 's3', title: 'Tie OOH presence to downstream search', subtitle: 'STRATIS HOLDS THE LINK LIVE', type: 'targeting', completed: false },
    ],
  },
];

export const AUTO_CONTEXT_VISUALS: Record<string, InsightVisual> = {
  // ── Region ──
  'ins-auto-geo-national': {
    kind: 'scatter', xKey: 'weight', series: ['conversion'],
    xName: 'Budget weight (index)', yName: 'Conversion vs national avg (%)',
    config: { conversion: { label: 'Province', color: PURPLE } },
    refLines: [{ axis: 'y', value: 0, label: 'National average', color: GOLD }],
    data: [
      { weight: 138, conversion: -22 }, { weight: 126, conversion: -14 }, { weight: 112, conversion: -8 },
      { weight: 96, conversion: 6 }, { weight: 78, conversion: 19 }, { weight: 64, conversion: 27 },
    ],
    caption: 'High-weight provinces converting below average (lower right) should fund the under-weighted winners (upper left)',
  },
  'ins-auto-geo-bc': {
    kind: 'bar', xKey: 'region', series: ['cpl'], perBarColor: true,
    yTitle: 'Cost per lead ($)',
    config: { cpl: { label: 'Cost per lead ($)' } },
    data: [
      { region: 'BC', cpl: 148, fill: TEAL },
      { region: 'AB', cpl: 210, fill: MUTED },
      { region: 'QC', cpl: 218, fill: MUTED },
      { region: 'AT', cpl: 232, fill: MUTED },
      { region: 'ON', cpl: 298, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 218, label: 'Tier 1 baseline $218', color: GRID }],
    caption: 'BC runs the proven playbook at ~$148 — the other four regions trail it',
  },
  'ins-auto-geo-alberta': {
    kind: 'bar', xKey: 'segment', series: ['conv', 'budget'],
    yTitle: 'Conversion idx · budget share %',
    config: { conv: { label: 'Conversion (idx)', color: TEAL }, budget: { label: 'Budget share %', color: PURPLE } },
    data: [
      { segment: 'Full-Size Truck', conv: 142, budget: 26 },
      { segment: 'Fleet / Commercial', conv: 138, budget: 12 },
      { segment: 'Passenger SUV', conv: 86, budget: 41 },
      { segment: 'EV', conv: 92, budget: 21 },
    ],
    caption: 'Alberta’s strongest segments (truck, fleet) draw the least budget',
  },
  'ins-auto-geo-ontario': {
    kind: 'bar', xKey: 'region', series: ['cpl'], perBarColor: true,
    yTitle: 'Cost per lead ($)',
    config: { cpl: { label: 'Cost per lead ($)' } },
    data: [
      { region: 'BC', cpl: 148, fill: MUTED },
      { region: 'Network avg', cpl: 218, fill: MUTED },
      { region: 'Ontario', cpl: 298, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 218, label: 'Network avg $218', color: GRID }],
    caption: 'Biggest regional budget, worst lead cost — the largest recovery in the portfolio',
  },
  'ins-auto-geo-quebec': {
    kind: 'bar', xKey: 'creative', series: ['index'], perBarColor: true,
    yTitle: 'Conversion index',
    config: { index: { label: 'Conversion (idx)' } },
    data: [
      { creative: 'Local French (regional)', index: 230, fill: TEAL },
      { creative: 'Adapted national cut', index: 100, fill: MUTED },
    ],
    refLines: [{ axis: 'y', value: 100, label: 'National baseline', color: GRID }],
    caption: 'Locally-built French creative converts ~2.3× the adapted national cut',
  },
  'ins-auto-geo-atlantic': {
    kind: 'line', xKey: 'spend', series: ['atlantic', 'headroom'],
    config: { atlantic: { label: 'Atlantic — new people reached', color: RED }, headroom: { label: 'Headroom provinces — new people', color: TEAL } },
    refLines: [{ axis: 'x', value: '$0.8M', label: 'Atlantic reach ceiling', color: GOLD }],
    data: [
      { spend: '$0.2M', atlantic: 17, headroom: 16 }, { spend: '$0.5M', atlantic: 11, headroom: 15 },
      { spend: '$0.8M', atlantic: 5, headroom: 15 }, { spend: '$1.1M', atlantic: 2, headroom: 14 },
      { spend: '$1.4M', atlantic: 1, headroom: 14 },
    ],
    caption: 'Past ~$0.8M Atlantic just adds frequency — provinces with headroom still find new people',
  },

  // ── Channel ──
  'ins-auto-ch-ctv': {
    kind: 'line', xKey: 'spend', series: ['ctv', 'search'],
    config: { ctv: { label: 'CTV — leads per +$100K', color: RED }, search: { label: 'Search — leads per +$100K', color: TEAL } },
    refLines: [{ axis: 'x', value: '$2.6M', label: 'CTV reach ceiling', color: GOLD }],
    data: [
      { spend: '$1.4M', ctv: 21, search: 23 }, { spend: '$2.0M', ctv: 14, search: 22 },
      { spend: '$2.6M', ctv: 7, search: 21 }, { spend: '$3.2M', ctv: 4, search: 20 },
      { spend: '$3.8M', ctv: 3, search: 19 },
    ],
    caption: 'Past ~$2.6M each extra CTV dollar adds frequency, not reach — search still converts',
  },
  'ins-auto-ch-instagram': {
    kind: 'line', xKey: 'week', series: ['cpm', 'cpl'],
    yTitle: 'Indexed to 100',
    config: { cpm: { label: 'Instagram CPM', color: RED }, cpl: { label: 'Cost per lead', color: TEAL } },
    data: [
      { week: 'W-3', cpm: 100, cpl: 100 }, { week: 'W-2', cpm: 110, cpl: 101 },
      { week: 'W-1', cpm: 118, cpl: 99 }, { week: 'Now', cpm: 122, cpl: 100 },
    ],
    caption: 'CPM up ~22% over three weeks while cost-per-lead held flat — paying more for the same',
  },
  'ins-auto-ch-facebook': {
    kind: 'scatter', xKey: 'overlap', series: ['cpm'], perBarColor: true,
    xName: 'Campaign overlap (%)', yName: 'CPM ($)',
    config: { cpm: { label: 'CPM ($)' } },
    legend: [
      { label: 'Contested in-market shopper', color: RED },
      { label: 'Non-contested audiences', color: MUTED },
    ],
    data: [
      { overlap: 7, cpm: 16, fill: MUTED, name: 'Non-contested' },
      { overlap: 14, cpm: 17, fill: MUTED, name: 'Non-contested' },
      { overlap: 23, cpm: 19, fill: MUTED, name: 'Non-contested' },
      { overlap: 38, cpm: 21, fill: MUTED, name: 'Non-contested' },
      { overlap: 61, cpm: 24, fill: RED, name: 'Contested in-market shopper', tag: 'Contested' },
    ],
    caption: 'More campaign overlap on the same Facebook shopper tracks higher CPM',
  },
  'ins-auto-ch-tiktok': {
    kind: 'bar', xKey: 'platform', series: ['cost'], perBarColor: true,
    yTitle: 'Cost per qualified visit ($)',
    config: { cost: { label: 'Cost per qualified visit ($)' } },
    data: [
      { platform: 'Meta (cold)', cost: 14.6, fill: RED },
      { platform: 'TikTok (younger conquest)', cost: 9.7, fill: TEAL },
    ],
    legend: [
      { label: 'TikTok — single-digit budget share', color: TEAL },
      { label: 'Meta cold prospecting — most of it', color: RED },
    ],
    caption: 'TikTok converts the younger conquest audience at ~2/3 of Meta’s cost',
  },
  'ins-auto-ch-google-search': {
    kind: 'bar', xKey: 'format', series: ['roas'], perBarColor: true,
    config: { roas: { label: 'ROAS' } },
    data: [
      { format: 'Vehicle Listing', roas: 5.7, fill: TEAL },
      { format: 'High-intent query', roas: 5.0, fill: TEAL },
      { format: 'Brand', roas: 3.1, fill: MUTED },
      { format: 'Generic nameplate', roas: 2.2, fill: RED },
    ],
    caption: 'High-intent formats convert ~2.6× the generic terms that hold the budget',
  },
  'ins-auto-ch-ttd': {
    kind: 'bar', xKey: 'route', series: ['waste'], perBarColor: true,
    yTitle: 'Spend lost to waste (%)',
    config: { waste: { label: 'Spend lost to waste (%)' } },
    data: [
      { route: 'Open exchange', waste: 26, fill: RED },
      { route: 'Curated deals (TTD)', waste: 5, fill: TEAL },
    ],
    legend: [
      { label: 'Unviewable / off-target / unsafe', color: RED },
      { label: 'Verified, on-topic inventory', color: TEAL },
    ],
    caption: 'Same audience, far less waste — curated deals put ~26% more of the dollar to work',
  },
  'ins-auto-ch-spotify': {
    kind: 'bar', xKey: 'plays', series: ['lift'], perBarColor: true,
    xTitle: 'Plays per week', yTitle: 'Incremental lift (idx)',
    config: { lift: { label: 'Incremental lift (idx)' } },
    data: [
      { plays: '1–3', lift: 100, fill: TEAL },
      { plays: '4–6', lift: 88, fill: TEAL },
      { plays: '7–8', lift: 64, fill: BLUE },
      { plays: '9–12', lift: 22, fill: RED },
      { plays: '13+', lift: 8, fill: RED },
    ],
    refLines: [{ axis: 'x', value: '7–8', label: 'Lift flattens (~8/wk)', color: GRID }],
    caption: 'Audio lift flattens past ~8 plays/week — two flights push the same listener past it',
  },
  'ins-auto-ch-linkedin': {
    kind: 'bar', xKey: 'channel', series: ['cost'], perBarColor: true,
    yTitle: 'Cost per qualified fleet lead ($)',
    config: { cost: { label: 'Cost per qualified fleet lead ($)' } },
    data: [
      { channel: 'LinkedIn', cost: 86, fill: TEAL },
      { channel: 'Search', cost: 132, fill: MUTED },
      { channel: 'Broad social', cost: 188, fill: RED },
    ],
    caption: 'LinkedIn delivers the cheapest qualified fleet lead — on a fraction of the budget',
  },
  'ins-auto-ch-ooh': {
    kind: 'line', xKey: 'lag', series: ['lift'],
    config: { lift: { label: 'Branded search lift after boards', color: TEAL } },
    refLines: [{ axis: 'x', value: '+5d', label: 'Search lift peaks', color: GOLD }],
    data: [
      { lag: '0d', lift: 12 }, { lag: '+2d', lift: 28 }, { lag: '+5d', lift: 41 },
      { lag: '+8d', lift: 33 }, { lag: '+12d', lift: 19 },
    ],
    caption: 'Branded search lifts after boards go live — but a third of boards sit in saturated markets',
  },
};
